#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grading):
    for i in range(len(grading)):
        nxt5 = math.ceil(grading[i] / 5) * 5 
        if grading[i] >= 38 and nxt5-grading[i]<3: 
            grading[i] = nxt5  
    return grading

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grading = []

    for x in range(grades_count):
        grades_item = int(input().strip())
        grading.append(grades_item)

    result = gradingStudents(grading)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
